package com.example.bookstore.service;
import com.example.bookstore.dto.*; import com.example.bookstore.entity.*; import com.example.bookstore.exception.*; import com.example.bookstore.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class BookService { private final BookRepository repo; private final AuthorRepository authors; private final CategoryRepository categories; public BookService(BookRepository repo,AuthorRepository authors,CategoryRepository categories){this.repo=repo;this.authors=authors;this.categories=categories;}
 @Transactional public BookResponse create(BookRequest r){if(repo.existsByIsbnIgnoreCase(r.isbn()))throw new ConflictException("Book with ISBN '"+r.isbn()+"' already exists");return BookResponse.from(repo.save(new Book(r.title(),r.isbn(),r.price(),r.stock(),r.publishedDate(),author(r.authorId()),category(r.categoryId()))));}
 @Transactional(readOnly=true) public Page<BookResponse> findAll(String keyword,Long authorId,Long categoryId,Pageable pageable){Page<Book> p;if(keyword!=null&&!keyword.isBlank())p=repo.searchByTitleOrAuthor(keyword.trim(),pageable);else if(authorId!=null)p=repo.findByAuthorId(authorId,pageable);else if(categoryId!=null)p=repo.findByCategoryId(categoryId,pageable);else p=repo.findAll(pageable);return p.map(BookResponse::from);}
 @Transactional(readOnly=true) public Book get(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Book with id "+id+" not found"));}
 @Transactional public BookResponse update(Long id,BookRequest r){Book b=get(id);if(repo.existsByIsbnIgnoreCaseAndIdNot(r.isbn(),id))throw new ConflictException("Book with ISBN '"+r.isbn()+"' already exists");b.update(r.title(),r.isbn(),r.price(),r.stock(),r.publishedDate(),author(r.authorId()),category(r.categoryId()));return BookResponse.from(b);}
 @Transactional public void delete(Long id){get(id);repo.deleteById(id);} private Author author(Long id){return authors.findById(id).orElseThrow(()->new ResourceNotFoundException("Author with id "+id+" not found"));} private Category category(Long id){return categories.findById(id).orElseThrow(()->new ResourceNotFoundException("Category with id "+id+" not found"));}
}
